version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: novel_evaluation_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-kakuyomu}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-evaluation}
      POSTGRES_DB: ${POSTGRES_DB:-novel_evaluation}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - novel_evaluation_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kakuyomu -d novel_evaluation"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: novel_evaluation_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - novel_evaluation_network
    depends_on:
      - postgres

networks:
  novel_evaluation_network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
